version: '3'

services:
  lvp:
    container_name: lvp
    depends_on: [db]
    environment:
      DB_HOST: db
      DB_NAME: lvp
      DB_USER: lvp
      DB_PASSWORD: lvp
      DB_PORT: 3306
    ports:
      - "80:80"
    volumes:
      - ./lvp/src:/var/www/html/lvp/src
      - ./lvp/tests:/var/www/html/lvp/tests

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: lvp
      MYSQL_USER: lvp
      MYSQL_PASSWORD: lvp
      MYSQL_ROOT_PASSWORD: lvp
    ports:
      - "3306:3306"